### ISSUE TITLE
Home page : The Height between the lead-ins and "we are GVR transport" title should be 76px, currently used 92px

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/G-V-Roberts#29]
![2](https://cloud.githubusercontent.com/assets/13309806/9896617/4a519a3c-5beb-11e5-95b0-9a1b2d2cc6c3.png)

**Comment by ganesh-titan** [comment]
Check Once, As per PSD the height between title and lead-ins is 67px.
