### ISSUE TITLE
Home - view our gallery: There should only be 12 images (latest) to be displayed to achieve the design layout (no pagination).  

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/G-V-Roberts#57]
![image](https://cloud.githubusercontent.com/assets/11186313/10362439/3640394c-6de1-11e5-8294-58213c501ad8.png)

**Comment by roseliesromeo** [comment]
Not fixed.  It should display the latest 12 images added in the gallery.
![image](https://cloud.githubusercontent.com/assets/11186313/10473670/9631efe8-7260-11e5-83ac-d7882d1b6b56.png)

**Comment by ganesh-titan** [comment]
Hi @roseliesromeo 
When you are adding gallery to home, you must have to give limit for gallery images. See Screenshot
![screen shot 2015-10-19 at 11 28 22](https://cloud.githubusercontent.com/assets/13450883/10570718/b21ce490-7654-11e5-967e-0d71c1debebf.png)

**Comment by roseliesromeo** [comment]
Hi @ganesh-titan,

Please include this specific instruction in the user guide.  I notice there is no instruction on how to add  gallery into the section. We'll mark this accordingly once done.

Thanks
